---
- name: Create directory and file on CentOS
  hosts: all
  become: yes
  gather_facts: no
  vars:
    ansible_remote_tmp: /tmp  # override to avoid issues with $HOME

  tasks:
    - name: Create /home/tmp directory
      file:
        path: /home/tmp
        state: directory
        mode: '0755'

    - name: Create /home/tmp/test.txt
      file:
        path: /home/tmp/test.txt
        state: touch
        mode: '0644'
