- name: Run inline bash script to create file
  hosts: all
  become: true
  tasks:
    - name: Create file using bash logic
      shell: |
        #!/bin/bash
        FILE_PATH="/home/test.txt"
        mkdir -p "$(dirname "$FILE_PATH")"
        touch "$FILE_PATH"
        echo "File created at $FILE_PATH"
