- name: Create a file in /home/cstadmin/test directory using shell command
  hosts: all
  become: true
  tasks:
    - name: Create /home/cstadmin/test/test.txt using shell
      shell: touch /home/cstadmin/test/test.txt
